(set-register ?z '(file . "~/zibaldone-Fall2020.org"))
(set-register ?m '(file . "~/Design/Metascape/Overview.org"))
(set-register ?r '(file . "~/.live-packs/marchdown-circe-pack/config/registers.el"))

;(set-register ?e '(file . "/code/prose/notes-on-emacs.md"))
(set-register ?i '(file . "~/.live-packs/marchdown-circe-pack/init.el"))
(set-register ?b '(file . "~/.live-packs/marchdown-circe-pack/config/bindings.el"))
;;(set-register ?s '(file . "~/Yandex.Disk/org/snippets.txt"))
(set-register ?s '(file . "~/.live-packs/marchdown-circe-pack/config/session-management.el"))
;;(set-register ?I '(file . "~/.emacs.d/init.el"))
(set-register ?e '(file . "~/.live-packs/marchdown-circe-pack/eye-candy.el"))
(set-register ?E '(file . "~/.emacs.d/init.d/eye-candy.el"))
;; Pehaps e-shell buffer? or Env/

(set-register ?n '(file . "~/Yandex.Disk/org/notes.org"))


;(set-register ?z '(file . "~/Yandex.Disk/org/commonplacebook.org"))
;(set-register ?t '(file . "~/documents/TODO.org"))
;(set-register ?s '(file . "~/src/safe/log.org"))
;(set-register ?x '(file . "~/.xbindkeysrc.scm"))
;;(set-register ?i '(file . "~/.emacs.d/init.el"))
;; (set-register ?o '(file . "~/Dropbox/org/README.org"))
;; (if (equal (shell-command-to-string "/usr/bin/whoami") "codepraxis\n") (set-register ?o '(file . "/infodump-codepraxis.org")))
;; (set-register ?x '(file . "~/.xmonad/xmonad.hs"))
;; (set-register ?r '(file . "~/.emacs.d/init.d/registers.el"))
;; (set-register ?t '(file . "~/org/tempus.org"))
;; (set-register ?g '(file . "~/.gitconfig"))
;; ;(set-register ?f '(file . "~/.emacs.d/funcs.el"))
;; ;(set-register ?k '(file . "~/.ssh/known_hosts"))
;; (set-register ?k '(file . "~/.emacs.d/init.d/keybindings.el"))
;; (set-register ?c '(file . "~/.ssh/config"))
;; (set-register ?l '(file . "~/.emacs.d/latex-config.el"))
;; ;(set-register ?e '(file . "/code/prose/notes-on-emacs.md"))
;; (set-register ?e '(file . "~/.emacs.d/init.d/eye-candy.el"))
;; (set-register ?n '(file . "~/Dropbox/org/notes.org"))
;; (set-register ?z '(file . "~/Dropbox/org/commonplacebook.org"))
;; ;(set-register ?t '(file . "~/documents/TODO.org"))
;; ;(set-register ?s '(file . "~/src/safe/log.org"))
;; ;(set-register ?x '(file . "~/.xbindkeysrc.scm"))
;; ;;(set-register ?i '(file . "~/.emacs.d/init.el"))
;; (set-register ?o '(file . "~/Dropbox/org/README.org"))
;; (if (equal (shell-command-to-string "/usr/bin/whoami") "codepraxis\n") (set-register ?o '(file . "/infodump-codepraxis.org")))
;; (set-register ?x '(file . "~/.xmonad/xmonad.hs"))
;; (set-register ?r '(file . "~/.emacs.d/init.d/registers.el"))
(set-register ?t '(file . "~/Yandex.Disk/org/tempus.org"))
;; (set-register ?g '(file . "~/.gitconfig"))
;; ;(set-register ?f '(file . "~/.emacs.d/funcs.el"))
(set-register ?k '(file . "~/.ssh/known_hosts"))
;; (set-register ?k '(file . "~/.emacs.d/init.d/keybindings.el"))
 (set-register ?c '(file . "~/.ssh/config"))
;; (set-register ?l '(file . "~/.emacs.d/latex-config.el"))
